apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nadra-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nadraacr.azurecr.io/nadra-backend:187a8b9bc19a9be51f1e3f2a14abb26faa97dfa8
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          value: nadra
        - name: DB_PASSWORD
          value: nadra123
        - name: DB_NAME
          value: nadradb
        ports:
        - containerPort: 3000
