apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nadra-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nadraacr.azurecr.io/nadra-frontend:71357d4639decadb34dbf0d9febc7ecefb30d949
        ports:
        - containerPort: 80
