apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nadra-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nadraacr.azurecr.io/nadra-frontend:7bf3bd718fd94b8a2304cd4bd72d6bc3292c5d60
        ports:
        - containerPort: 80
