apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nadra-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nadraacr.azurecr.io/nadra-frontend:71afcbc52e924f93bf9f5ff0cd9f1d076e8a31af
        ports:
        - containerPort: 80
