apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: nadra-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: nadradb
        - name: POSTGRES_USER
          value: nadra
        - name: POSTGRES_PASSWORD
          value: nadra123
        ports:
        - containerPort: 5432
